<?php

namespace test;

use PHPUnit\Framework\TestCase;
use function app\util\get_config;
use function app\util\get_db_conn;

class UtilTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $_SERVER["DOCUMENT_ROOT"] = dirname(__DIR__);
    }

    public function test_get_config()
    {
        require_once $_SERVER["DOCUMENT_ROOT"] . "/app/util.php";
        $config = get_config();
        $this->assertTrue($config != false);
    }

    public function test_get_conn()
    {
        require_once $_SERVER["DOCUMENT_ROOT"] . "/app/util.php";
        $conn = get_db_conn();
        $this->assertTrue($conn != false);
    }

}
