<?php

namespace test;

use PHPUnit\Framework\TestCase;
use function app\util\get_config;
use function app\util\get_db_conn;

class UtilTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $_SERVER["DOCUMENT_ROOT"] = dirname(__DIR__);
    }

    public function test_get_config()
    {
        require_once $_SERVER["DOCUMENT_ROOT"] . "/app/util.php";
        $config = get_config();
        $this->assertTrue($config != false);
    }

    public function test_get_conn()
    {
        require_once $_SERVER["DOCUMENT_ROOT"] . "/app/util.php";
        $conn = get_db_conn();
        $this->assertTrue($conn != false);
    }

    public function test_session()
    {
        require_once $_SERVER["DOCUMENT_ROOT"] . "/app/util.php";
        $datetime = date("Y-m-d H:i:s");
        $conn = get_db_conn();
        $query = <<<QUERY
SELECT expired_at
FROM sessions
WHERE id="test";
QUERY;
        $result = mysqli_query($conn, $query);
        if (mysqli_num_rows($result) == 0) {
            $this->alert_login();
        }
        $row = mysqli_fetch_row($result);
        $expired_at = $row[0];
        var_dump($datetime, $expired_at);
        $this->assertTrue(true);
        var_dump(strtotime($expired_at));
        var_dump(strtotime("now"));

    }
}
